name: Release

on:
  push:
    tags:
      - 'v*'
env:
    GO_VERSION: 1.21
jobs:
  goreleaser:
    runs-on: ubuntu-20.04
    steps:
      - name: Install libpcap
        run: sudo apt-get install -y libpcap-dev
      - name: Checkout Source Code
        uses: actions/checkout@v2  # Using v2 instead of v3
      - name: Setup Go Environment
        uses: actions/setup-go@v2  # Using v2 instead of v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Install GoReleaser
        run: |
          GO111MODULE=on go get github.com/goreleaser/goreleaser
          sudo mv $GOPATH/bin/goreleaser /usr/local/bin/goreleaser
      - name: Run GoReleaser
        run: goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
